/**
 * 「运行一条项目命令」——默认**后台静默**跑，也可以交给宿主机自己的某个终端。
 *
 * 为什么不自己起 PTY：Pi Desktop 没有内嵌终端。终端模式把命令交给系统终端，用户拿到的
 * 就是平常那个 shell（代价最小、最不意外）；后台模式则完全不弹窗，stdout/stderr 落进
 * `<tmpdir>/pi-desktop-run/logs/` 下的日志文件，界面上给一个「查看日志」入口。
 *
 * macOS / Linux 上先把「cd + 命令」写成临时 `.command` 脚本再交给终端，而不是把命令拼进
 * AppleScript / `-e` 字符串里：脚本从文件读，引号、空格、`&&` 都不用转义，少一整类注入 bug。
 * 后台模式不写脚本，直接 `sh -lc`，stdout 重定向到日志文件。
 */
import { spawn } from "node:child_process";
import { chmodSync, closeSync, existsSync, mkdirSync, openSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join, resolve, sep } from "node:path";
import { tmpdir } from "node:os";

import { launchDetached } from "./openDiff.mjs";

/** 临时脚本都放这里：`<tmpdir>/pi-desktop-run/`。 */
export const RUN_SCRIPT_ROOT = "pi-desktop-run";
/** 后台运行日志放这里（`RUN_SCRIPT_ROOT` 下面）。 */
export const RUN_LOG_ROOT = join(RUN_SCRIPT_ROOT, "logs");
/** 后台运行模式的 launcher 标记（前端据此判断要不要显示「查看日志」）。 */
export const BACKGROUND_LAUNCHER = "background";
/** 超过这个年龄的旧脚本 / 旧日志在下次运行时清掉（七天），临时目录不会无上限长大。 */
export const RUN_SCRIPT_MAX_AGE_MS = 7 * 24 * 60 * 60 * 1000;

/** POSIX 单引号包裹。命令和工作目录都要经过它，空格、引号、`$` 都原样传给 shell。 */
export function shellQuote(value) {
  return `'${String(value ?? "").replace(/'/g, "'\\''")}'`;
}

/**
 * 临时脚本正文：进项目目录 → 跑命令 → 打完退出码后留一个交互 shell。
 *
 * 留 shell 是为了命令失败时窗口不闪退 —— 用户还能看见上面那行错误，也能接着敲命令。
 */
export function runScriptText(command, cwd) {
  return [
    "#!/bin/sh",
    "# Generated by Pi Desktop: run one project command in a fresh terminal.",
    `cd ${shellQuote(cwd)} || exit 1`,
    String(command ?? "").trim(),
    "status=$?",
    "printf '\\n[Pi Desktop] command exited with status %s\\n' \"$status\"",
    'exec "${SHELL:-/bin/sh}" -l',
    "",
  ].join("\n");
}

/** 终端 app 名的形态卫生：`open -a` 不接受空/奇怪字符，也顺手挡住注入。 */
export function normalizeTerminalApp(value) {
  const text = String(value ?? "").trim();
  return /^[\w .+-]{1,64}$/.test(text) ? text : "";
}

/**
 * 终端启动候选，按顺序试；第一个真的把进程拉起来就算成功。
 *
 * 每个候选是一组 step：组内顺序执行，非 `optional` 的 step 失败就换下一组。这样「没装
 * iTerm / 没有 Windows Terminal」不会变成报错，只是回退到下一个。
 *
 * `terminalApp`（或 `PI_DESKTOP_TERMINAL`）可以指定 macOS 上优先用的终端 app 名（默认
 * `Terminal`）。Windows / Linux 目前仍按固定候选链，忽略这个值。
 */
export function terminalLauncherPlans({ platform = process.platform, scriptPath, command, cwd, env = process.env, terminalApp = "" } = {}) {
  if (platform === "darwin") {
    const app = normalizeTerminalApp(terminalApp) || String(env?.PI_DESKTOP_TERMINAL ?? "").trim() || "Terminal";
    const steps = [{ command: "open", args: ["-a", app, scriptPath] }];
    // 后台进程启动的窗口不一定到前台；补一次 AppleScript 抬起来（失败无所谓）。
    if (/^[\w .+-]+$/.test(app)) {
      steps.push({ command: "osascript", args: ["-e", `tell application "${app}" to activate`], optional: true });
    }
    return [steps];
  }

  if (platform === "win32") {
    return [
      [
        {
          command: "cmd",
          args: ["/c", "start", "", "cmd.exe", "/k", `cd /d "${cwd}" && ${command}`],
        },
      ],
    ];
  }

  const shells = [
    ["x-terminal-emulator", ["-e", "sh", scriptPath]],
    ["gnome-terminal", ["--", "sh", scriptPath]],
    ["konsole", ["-e", "sh", scriptPath]],
    ["xfce4-terminal", ["-e", `sh ${shellQuote(scriptPath)}`]],
    ["xterm", ["-e", "sh", scriptPath]],
  ];
  return shells.map(([binary, args]) => [{ command: binary, args }]);
}

/**
 * 后台运行的启动计划：不弹窗，直接一个 shell 跑命令，stdout/stderr 由调用方重定向到日志。
 * `-lc` 让命令拿到和登录 shell 接近的 PATH（`npm` / `node` 之类才找得到）。
 */
export function backgroundCommandPlan({ platform = process.platform, command, cwd } = {}) {
  if (platform === "win32") {
    return { command: "cmd", args: ["/c", String(command ?? "").trim()], cwd };
  }
  return { command: "/bin/sh", args: ["-lc", String(command ?? "").trim()], cwd };
}

/** 清掉目录里超过 `maxAgeMs` 的文件；目录不存在 / 删不掉都当没事。 */
function sweepDirectory(directory, { now, maxAgeMs }) {
  let entries;
  try {
    entries = readdirSync(directory);
  } catch {
    return;
  }
  for (const name of entries) {
    const path = join(directory, name);
    try {
      if (now - statSync(path).mtimeMs > maxAgeMs) {
        rmSync(path, { force: true });
      }
    } catch {
      // 删不掉（权限/竞态）无所谓，下次再试。
    }
  }
}

/** 清掉过期的临时脚本与后台日志；找不到目录就当没有。 */
export function sweepRunScripts({ baseDir = tmpdir(), now = Date.now(), maxAgeMs = RUN_SCRIPT_MAX_AGE_MS } = {}) {
  sweepDirectory(join(baseDir, RUN_SCRIPT_ROOT), { now, maxAgeMs });
  sweepDirectory(join(baseDir, RUN_LOG_ROOT), { now, maxAgeMs });
}

/** 项目目录校验：非空、存在、且真的是目录。 */
function requireProjectDirectory(cwd, exists) {
  const directory = String(cwd ?? "").trim();
  if (!directory || !exists(directory) || !statSync(directory).isDirectory()) {
    throw new Error(`项目目录不存在：${directory || "(空)"}`);
  }
  return directory;
}

function requireCommand(command) {
  const text = String(command ?? "").trim();
  if (!text) {
    throw new Error("没有可运行的命令。");
  }
  return text;
}

/**
 * 后台静默运行：spawn 一个 detached 的 shell，stdout/stderr 追加到日志文件。
 *
 * 日志先写好头（命令 / 目录 / pid / 时间），再用 append 模式把 fd 交给子进程 —— 用
 * `writeFileSync` 写头会截断子进程已写出的内容（顺序反过来就丢日志）。
 */
export async function runProjectCommandInBackground(command, cwd, {
  spawnImpl = spawn,
  platform = process.platform,
  baseDir = tmpdir(),
  now = Date.now(),
  exists = existsSync,
} = {}) {
  const text = requireCommand(command);
  const directory = requireProjectDirectory(cwd, exists);

  sweepRunScripts({ baseDir, now });

  const logDir = join(baseDir, RUN_LOG_ROOT);
  mkdirSync(logDir, { recursive: true });
  const logPath = join(logDir, `run-${now.toString(36)}-${Math.random().toString(36).slice(2, 8)}.log`);
  const plan = backgroundCommandPlan({ platform, command: text, cwd: directory });

  writeFileSync(
    logPath,
    [
      "# Pi Desktop 后台运行",
      `# command: ${text}`,
      `# cwd: ${directory}`,
      `# started: ${new Date(now).toISOString()}`,
      "",
    ].join("\n"),
  );

  const fd = openSync(logPath, "a");
  let pid;
  try {
    pid = await new Promise((resolvePromise, reject) => {
      let child;
      try {
        child = spawnImpl(plan.command, plan.args, { cwd: directory, detached: true, stdio: ["ignore", fd, fd] });
      } catch (error) {
        reject(error);
        return;
      }
      child.once("error", reject);
      child.once("spawn", () => {
        child.unref?.();
        resolvePromise(child.pid);
      });
    });
  } finally {
    closeSync(fd);
  }

  return { launcher: BACKGROUND_LAUNCHER, logPath, pid, command: text, cwd: directory };
}

/**
 * 在系统终端里跑一条命令，返回实际用到的终端。
 *
 * 只在用户点「运行」时调用，且命令来自项目自己的命令列表（用户自己选的）。这里不解析
 * 命令内容 —— 它就是用户想跑的那串东西。
 *
 * `background: true` 走上面的静默路径；否则按 `terminalApp` 打开一个终端窗口。
 */
export async function runProjectCommand(
  command,
  cwd,
  {
    spawnImpl,
    platform = process.platform,
    env = process.env,
    baseDir = tmpdir(),
    now = Date.now(),
    exists = existsSync,
    terminalApp = "",
    background = false,
  } = {},
) {
  if (background) {
    return runProjectCommandInBackground(command, cwd, { spawnImpl, platform, baseDir, now, exists });
  }

  const text = requireCommand(command);
  const directory = requireProjectDirectory(cwd, exists);

  sweepRunScripts({ baseDir, now });

  const scriptPath = join(baseDir, RUN_SCRIPT_ROOT, `run-${now.toString(36)}.command`);
  mkdirSync(join(baseDir, RUN_SCRIPT_ROOT), { recursive: true });
  writeFileSync(scriptPath, runScriptText(text, directory), { mode: 0o755 });
  try {
    chmodSync(scriptPath, 0o755);
  } catch {
    // 某些文件系统（Windows 挂载盘）不支持，忽略：Windows 分支根本不用这个脚本。
  }

  const plans = terminalLauncherPlans({ platform, scriptPath, command: text, cwd: directory, env, terminalApp });
  let lastError;
  for (const steps of plans) {
    try {
      for (const step of steps) {
        try {
          await launchDetached(step.command, step.args, spawnImpl ? { spawnImpl } : {});
        } catch (error) {
          if (!step.optional) {
            throw error;
          }
        }
      }
      return { launcher: steps[0].command, scriptPath };
    } catch (error) {
      lastError = error;
    }
  }

  throw lastError ?? new Error("找不到可用的终端。");
}

/** macOS 上常见的终端 app（按这几个关键词匹配 `/Applications` 里的 `.app`）。 */
const MAC_TERMINAL_APP_NAMES = ["Terminal", "iTerm", "Warp", "Alacritty", "WezTerm", "kitty", "Ghostty", "Hyper", "Tabby", "Rio", "Wave"];

/**
 * 探测系统里装了哪些终端 app（目前只对 macOS 有意义：`open -a <name>`）。
 *
 * 只做「只读扫描」：列 `/Applications` 与 `~/Applications`，按已知名字过滤。Terminal 永远
 * 在列表里、且排第一（系统自带）。非 macOS 返回空数组，前端就只显示「系统默认终端」。
 */
export function detectTerminalApps({
  platform = process.platform,
  readdir = readdirSync,
  exists = existsSync,
  home = homedir(),
} = {}) {
  if (platform !== "darwin") {
    return [];
  }
  const dirs = ["/Applications", join(home, "Applications")];
  const found = new Set();
  for (const dir of dirs) {
    if (!exists(dir)) {
      continue;
    }
    let entries;
    try {
      entries = readdir(dir);
    } catch {
      continue;
    }
    for (const name of entries) {
      if (!String(name).endsWith(".app")) {
        continue;
      }
      const base = String(name).slice(0, -4);
      if (MAC_TERMINAL_APP_NAMES.some((known) => base.toLowerCase().includes(known.toLowerCase()))) {
        found.add(base);
      }
    }
  }
  const list = [...found].sort((a, b) => (a === "Terminal" ? -1 : b === "Terminal" ? 1 : a.localeCompare(b)));
  if (!list.includes("Terminal")) {
    list.unshift("Terminal");
  }
  return list;
}

/** 日志路径必须在运行日志目录里，别让渲染层传任意路径去打开。 */
export function isRunLogPath(logPath, baseDir = tmpdir()) {
  const dir = resolve(baseDir, RUN_LOG_ROOT);
  return resolve(String(logPath ?? "")).startsWith(dir + sep);
}

/** 「查看日志」：用系统默认程序打开日志文件（macOS `open` / Linux `xdg-open` / Windows `start`）。 */
export async function revealRunLog(logPath, { baseDir = tmpdir(), platform = process.platform, spawnImpl = spawn } = {}) {
  if (!isRunLogPath(logPath, baseDir)) {
    throw new Error("日志路径不在运行日志目录里。");
  }
  const plan =
    platform === "darwin"
      ? { command: "open", args: [logPath] }
      : platform === "win32"
        ? { command: "cmd", args: ["/c", "start", "", logPath] }
        : { command: "xdg-open", args: [logPath] };
  await new Promise((resolvePromise, reject) => {
    let child;
    try {
      child = spawnImpl(plan.command, plan.args, { stdio: "ignore", detached: true });
    } catch (error) {
      reject(error);
      return;
    }
    child.once("error", reject);
    child.once("spawn", () => {
      child.unref?.();
      resolvePromise();
    });
  });
}